name: Integration
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
jobs:
  Action:
    name: Test Inspector Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make changes to schema
        run: |
          sed --i 's/createdAt: String/createdAt: String!/g' ./example/schemas/schema.graphql
          cat ./example/schemas/schema.graphql
      - name: Run Inspector
        uses: ./
        id: inspector
        with:
          schema: "master:example/schemas/schema.graphql"

      - name: Validate result
        if: steps.inspector.outputs.changes != 3
        run: echo 'Expected 3 changes received ${{ steps.inspector.outputs.changes }}' && exit 1
