name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16, 18]
    env:
      CI: true

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Get pnpm cache - Set output
        id: pnpm-cache
        run: echo "{dir}={pnpm cache dir}" >> $GITHUB_OUTPUT

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ${ env.dir }
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Lint ESLint
        run: pnpm lint

      - name: Lint Prettier
        run: pnpm lint:prettier

      - name: Integration tests
        run: |
          chmod +x ./packages/cli/dist/index.js

          echo 2001
          ./packages/cli/dist/index.js validate './integration_tests/2001/operations/**/*.graphql' './integration_tests/2001/schema.graphql'

          echo 1991
          ./packages/cli/dist/index.js validate './integration_tests/1991/two-operations.js' './integration_tests/1991/schema.graphql'

          echo 1985
          ./packages/cli/dist/index.js introspect ./integration_tests/1985/schema.js || echo 'TODO'

          echo 2108
          ./packages/cli/dist/index.js introspect './integration_tests/2108/**/!(excluded)/*.graphql' --write ./2108.graphql
            if grep -ic "bar" ./2108.graphql
            then echo "Broken" && exit 1
            else echo "Works"
            fi

          echo 2027
          ./packages/cli/dist/index.js diff ./integration_tests/2027/schema-before.graphql ./integration_tests/2027/schema-after.graphql --rule considerUsage --onUsage ./integration_tests/2027/unused-hotels.js

          echo 2088
          ./packages/cli/dist/index.js diff ./integration_tests/2088/old.graphql ./integration_tests/2088/new.graphql --rule suppressRemovalOfDeprecatedField
